# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='node_key',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
