# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170523_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name_plural': 'log entries'},
        ),
        migrations.AddField(
            model_name='host',
            name='invalidate',
            field=models.BooleanField(default=False),
        ),
    ]
