# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170524_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='architecture',
            field=models.CharField(default='Unknown', help_text='Machine architecture.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='cpu',
            field=models.CharField(default='Unknown', help_text='Model of CPU installed.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='ram',
            field=models.IntegerField(default=0, help_text='Amount of RAM installed (octets).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='release',
            field=models.CharField(default='Unknown', help_text='Operating system release.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='identifier',
            field=models.CharField(help_text='Unique identifier for this system (usually hostname).', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='invalidate',
            field=models.BooleanField(default=False, help_text='Whether this node should be re-enrolled from scratch next time it checks in.'),
        ),
    ]
