# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170524_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of package from the operating system's package manager.", max_length=200)),
                ('version', models.CharField(help_text="The package manager's version for this package.", max_length=200)),
                ('architecture', models.CharField(help_text='Package architecture, which may differ from the host architecture.', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, help_text='Last time this host checked in.'),
        ),
        migrations.AlterField(
            model_name='host',
            name='node_key',
            field=models.CharField(help_text='Secret key this host uses to identify itself.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='ram',
            field=models.IntegerField(help_text='Amount of RAM installed (KiB).'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([('node_key', 'identifier')]),
        ),
        migrations.AddField(
            model_name='package',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([('name', 'host', 'architecture')]),
        ),
    ]
