# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170524_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
