# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_package_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(db_index=True, help_text="Name of package from the operating system's package manager.", max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='version',
            field=models.CharField(db_index=True, help_text="The package manager's version for this package.", max_length=200),
        ),
    ]
