# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170525_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for the query', max_length=255)),
                ('query', models.CharField(help_text='The query to be executed', max_length=255)),
                ('interval', models.IntegerField(default=10, help_text='How often should the query be run (in seconds)?')),
            ],
            options={
                'verbose_name_plural': 'log queries',
            },
        ),
    ]
