# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171118_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ram',
            field=models.BigIntegerField(blank=True, help_text='Amount of RAM installed (KiB).'),
        ),
    ]
