# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171118_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='identifier',
            field=models.CharField(db_index=True, help_text='Unique identifier for this system (usually hostname).', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([]),
        ),
    ]
