# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171118_2132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='package',
            name='host',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
