# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171119_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Name of package from the operating system's package manager.", max_length=200)),
                ('version', models.CharField(db_index=True, help_text="The package manager's version for this package.", max_length=200)),
                ('architecture', models.CharField(help_text='Package architecture, which may differ from the host architecture.', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([('name', 'host', 'architecture')]),
        ),
    ]
