# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upstream_id', models.CharField(help_text='The ID used by the vendor to refer to this advisory', max_length=200, verbose_name='Upstream ID')),
                ('short_description', models.CharField(help_text='One-line description of the advisory', max_length=200, null=True)),
                ('description', models.TextField(help_text='Longer description of the advisory', null=True)),
                ('action', models.TextField(help_text='What, if any, actions need to be taken to address the advisory', null=True)),
                ('issued', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which the advisory was issued')),
                ('source', models.CharField(choices=[('ubuntu', 'Ubuntu'), ('debian', 'Debian')], help_text='Vendor source of the advisory', max_length=32)),
                ('search_keywords', models.TextField(blank=True, help_text='Space separated list of keywords used to speed up search', null=True)),
            ],
            options={
                'ordering': ['-issued'],
                'verbose_name_plural': 'advisories',
            },
        ),
        migrations.CreateModel(
            name='BinaryPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(help_text='Name of binary package', max_length=200)),
                ('release', models.CharField(choices=[('jessie', 'Debian Jessie 8.0'), ('precise', 'Ubuntu Precise LTS 12.04'), ('trusty', 'Ubuntu Trusty LTS 14.04')], help_text='Specific release to which this package belongs', max_length=32)),
                ('safe_version', models.CharField(help_text="Package version that is to be considered 'safe' at the issue of this advisory", max_length=200, null=True)),
                ('architecture', models.CharField(help_text='Machine architecture', max_length=200, null=True)),
                ('advisory', models.ForeignKey(help_text='Advisory to which this package belongs', on_delete=django.db.models.deletion.CASCADE, to='advisories.Advisory')),
            ],
            options={
                'ordering': ['-package'],
                'verbose_name_plural': 'binary packages',
            },
        ),
        migrations.CreateModel(
            name='SourcePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(help_text='Name of source package', max_length=200)),
                ('release', models.CharField(choices=[('jessie', 'Debian Jessie 8.0'), ('precise', 'Ubuntu Precise LTS 12.04'), ('trusty', 'Ubuntu Trusty LTS 14.04')], help_text='Specific release to which this package belongs', max_length=32)),
                ('safe_version', models.CharField(help_text="Package version that is to be considered 'safe' at the issue of this advisory", max_length=200)),
                ('advisory', models.ForeignKey(help_text='Advisory to which this package belongs', on_delete=django.db.models.deletion.CASCADE, to='advisories.Advisory')),
            ],
            options={
                'ordering': ['-package'],
                'verbose_name_plural': 'source packages',
            },
        ),
        migrations.AddField(
            model_name='binarypackage',
            name='source_package',
            field=models.ForeignKey(blank=True, help_text='If set, the source package from which this binary package was generated', null=True, on_delete=django.db.models.deletion.CASCADE, to='advisories.SourcePackage'),
        ),
    ]
